### ISSUE TITLE
Privacy settings for players

### ISSUE THREAD

**Issue by Jonny134** [LadyDefile/simple-tickers#1]
I really like it, but it would be really nice if the Gm would see the players clocks or even better if the players could change the privacy settings of their clocks.

**Comment by MythicPalette** [comment]
This is actually already implemented now.

**Comment by Jonny134** [comment]
thank you

**Comment by MythicPalette** [comment]
Absolutely! Happy to help.

**Comment by Jonny134** [comment]
> Absolutely! Happy to help.

For some reason the module will not update for me to the latest version....

**Comment by Jonny134** [comment]
> This is actually already implemented now.

I dont see this implemented. This is what i see from players side. there is no option to set privacy. 
![image](https://github.com/LadyDefile/simple-tickers/assets/70774182/c98c6e41-2b27-4ff6-bb61-7ca03c461d50)

**Comment by MythicPalette** [comment]
> > This is actually already implemented now.
> 
> I dont see this implemented. This is what i see from players side. there is no option to set privacy. ![image](https://private-user-images.githubusercontent.com/70774182/324207402-c98c6e41-2b27-4ff6-bb61-7ca03c461d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjY1MDIsIm5iZiI6MTcxMzk2NjIwMiwicGF0aCI6Ii83MDc3NDE4Mi8zMjQyMDc0MDItYzk4YzZlNDEtMmIyNy00ZmY2LWJiNjEtN2NhMDNjNDYxZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEzNDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzY2VkYTA5NzAyYWMyYWQwNGE5NjhmZjE5NWM1NjViMGRjOTgwNTQzNmRmMDc2NzdjNGY3MjZlNDVmNTIzZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cCQsWneUaAU5iAOvzyoGMpgJ1GT8aG41TCCi4eqCMUw)

I'll look into it. I'm sure I'm doing something wrong with how I try to get the update working. You *should* be seeing this from the player view 
![image](https://github.com/LadyDefile/simple-tickers/assets/67084868/d6535225-aa0b-48a6-92ae-9a6ff42122ba)

This was captured on a player screen for me.

**Comment by MythicPalette** [comment]
This SHOULD be fixed now. I apologize for the weight. I just did something dumb is all. It should update properly in Foundry now.
