### ISSUE TITLE
Feature Request: Party Ticker

### ISSUE THREAD

**Issue by ttocs240** [LadyDefile/simple-tickers#2]
It would be cool to have a public group of tickers that can be progressed by anyone in the game to track group goals and long-term projects. I know the GM could do it and just tick it themselves, but having any player be able to progress the clock would be great.

**Comment by MythicPalette** [comment]
Ok, so you're thinking a ticker that is owned by the entire group, right? I can definitely do that!

**Comment by ttocs240** [comment]
Yeah, exactly! Hopefully isn't too difficult to do

**Comment by MythicPalette** [comment]
I've already got basic functionality for it done. Here is a little preview!
![image](https://github.com/LadyDefile/simple-tickers/assets/67084868/fe6e8c19-aeaa-46d0-a5e1-1b360077d8ab)
![image](https://github.com/LadyDefile/simple-tickers/assets/67084868/dfcb3cc2-8722-40e0-abd6-6f595f2f85d1)

It obviously requires more testing but I think I've got it nailed down. When you create/edit a ticker, you can mark it as shared. Shared tickers can be incremented/decremented by anyone. Only the creator of the ticker can change it's name, shared state, and delete it.

**Comment by ttocs240** [comment]
That was so fast! Thank you very much

**Comment by MythicPalette** [comment]
The update is uploaded. You should be able to update in your Foundry VTT any time now!
