### ISSUE TITLE
Feature Request: Allow GMs to edit/delete "Shared" tickers

### ISSUE THREAD

**Issue by ttocs240** [LadyDefile/simple-tickers#3]
I love the new feature! But if a shared ticker is created by a player, the GM does not have edit/delete permissions.

**Comment by MythicPalette** [comment]
Sorry for the late response, I had some stuff keeping me busy for a few days. This is definitely something I plan to look into but it might take me a little while to get it working right.

**Comment by MythicPalette** [comment]
I'm so sorry that this feature is currently so delayed. Unfortunately, my computer had a hardware failure and I've been busy reinstalling Windows and all of my various programs as well as getting all those things et back up how I like them. I just want you to know, it's still something I intend to work on.

**Comment by ttocs240** [comment]
No worries at all! Not like it's game-breaking by any means. Whenever you have the time. :)

**Comment by MythicPalette** [comment]
Feature implemented and will be available in the next release!
